matter/wifi/rs911x/rsi_if.c
matter/wifi/rs911x/wfx_rsi.h
matter/wifi/rs911x/wfx_rsi_host.c
matter/wifi/wf200/host_if.cpp

The disconnection from connected AP was not present in RS911x and WF200
Added support to disconnect node from a connected AP.
Tested manually using MG12+RS911x and MG12+WF200

Added disconnection support from connected AP in RS911x and WF200

---

matter/wifi/rs911x/hal/rsi_board_configuration.h

What is being fixed? What is the feature being added? Examples:
Added board configs for MG24 (4186C and 4187C) in rs911x
What's in this PR
Boards (BRD4186C/4187C) have been added in rsi_board_configuration.h file
How was this tested?
Manually tested with MG24 and RS916

Added board configs for MG24 4186C and 4187C

---

matter/wifi/wf200/host_if.cpp

Problem:
While commissioning sometimes we are getting the access point not found an issue because the scan default parameter is very few so the WF200 is not able to find the ap sometimes.
Change Overview
The default time is changed to a new time 
Active channel = 110 TU's (1TU = 1.024 ms).
Testing
Tested manually by using
MG12+WF200
RaspberryPi 4

Adds fix for AP not found issue while commissioning #21

---

matter/efr32/efr32mg24/BRD2703A/autogen/sl_event_handler.c

BRD2703a do not build for release or specific build arguments.
Align includes, init calls, and #ifdefs to match other mg24 boards
Remove unused/untested init calls for now (aka MPU, AES,some bluetooth calls( 
Build apps in release for this board

Align brd2703a event_handler file with the other mg24 boards. 

---

matter/efr32/efr32mg12/BRD4164A/config/sl_board_control_config.h
matter/efr32/efr32mg24/BRD4187A/config/sl_board_control_config.h

When the disable_lcd build argument is enabled for BRD4164A, spotting on the LCD screen can be observed.
Change the default of the DISP_ENABLE signal from 1 to 0. 
Tested on BRD4164A. Tested a build that enables the LCD, and tested a build that disables the LCD. Both have expected behavior with no spotting.

Fix potential LCD spotting on BRD4164A and BRD4187A when lcd screen is disabled

---

matter/efr32/mgm24/BRD4317A/autogen/sl_event_handler.c

* Missing ble RTOS init for the BRD4317A
* Add init function in the kernal start

Add Missing BLE init function for BRD4317A

---

matter/efr32/mgm24/BRD4317A/autogen/sl_event_handler.c

An bt rtos init call was added to the matter_1.0 branch when it shouldn't have. BT refactor is not in 1.0
Removing the bt rtos init call

Remove bt rtos init call from 1.0

---

matter/efr32/efr32mg12/BRD4163A/autogen/sl_component_catalog.h
matter/efr32/efr32mg12/BRD4163A/autogen/sl_event_handler.c
matter/efr32/efr32mg12/BRD4163A/autogen/sl_spidrv_init.c
matter/efr32/efr32mg12/BRD4163A/autogen/sl_spidrv_instances.h
matter/efr32/efr32mg12/BRD4163A/config/brd4161a.h
matter/efr32/efr32mg12/BRD4163A/config/sl_spidrv_exp_config.h
matter/efr32/efr32mg12/BRD4163A/config/spidrv_config.h
matter/efr32/efr32mg12/BRD4164A/autogen/sl_component_catalog.h
matter/efr32/efr32mg12/BRD4164A/autogen/sl_event_handler.c
matter/efr32/efr32mg12/BRD4164A/autogen/sl_spidrv_init.c
matter/efr32/efr32mg12/BRD4164A/autogen/sl_spidrv_instances.h
matter/efr32/efr32mg12/BRD4164A/config/brd4161a.h
matter/efr32/efr32mg12/BRD4164A/config/sl_spidrv_exp_config.h
matter/efr32/efr32mg12/BRD4164A/config/spidrv_config.h
matter/efr32/efr32mg12/BRD4170A/autogen/sl_component_catalog.h
matter/efr32/efr32mg12/BRD4170A/autogen/sl_event_handler.c
matter/efr32/efr32mg12/BRD4170A/autogen/sl_spidrv_init.c
matter/efr32/efr32mg12/BRD4170A/autogen/sl_spidrv_instances.h
matter/efr32/efr32mg12/BRD4170A/config/brd4161a.h
matter/efr32/efr32mg12/BRD4170A/config/sl_spidrv_exp_config.h
matter/efr32/efr32mg12/BRD4170A/config/spidrv_config.h

What is being fixed? What is the feature being added? Examples:
* Added changes to initialize MG12 - 70A/63A/64A Boards
* Changes include Wi-Fi initialization and SPI pin Configuration w.r.t RS9116 and WF200
How was this tested?
Manually Tested below scenario's
* Build is successful
* Commissioning is successful
* Sanity completed with MG12-70A/63A/64A with RS9116 and WF200 on one application (Lighting App).

[EFR32] MG12 63A/64A/70A Board bring up

---

matter/efr32/efr32mg12/BRD4163A/autogen/sl_component_catalog.h
matter/efr32/efr32mg12/BRD4163A/autogen/sl_event_handler.c
matter/efr32/efr32mg12/BRD4163A/autogen/sl_spidrv_init.c
matter/efr32/efr32mg12/BRD4163A/autogen/sl_spidrv_instances.h
matter/efr32/efr32mg12/BRD4163A/config/brd4161a.h
matter/efr32/efr32mg12/BRD4163A/config/sl_spidrv_exp_config.h
matter/efr32/efr32mg12/BRD4163A/config/spidrv_config.h
matter/efr32/efr32mg12/BRD4164A/autogen/sl_component_catalog.h
matter/efr32/efr32mg12/BRD4164A/autogen/sl_event_handler.c
matter/efr32/efr32mg12/BRD4164A/autogen/sl_spidrv_init.c
matter/efr32/efr32mg12/BRD4164A/autogen/sl_spidrv_instances.h
matter/efr32/efr32mg12/BRD4164A/config/brd4161a.h
matter/efr32/efr32mg12/BRD4164A/config/sl_spidrv_exp_config.h
matter/efr32/efr32mg12/BRD4164A/config/spidrv_config.h
matter/efr32/efr32mg12/BRD4170A/autogen/sl_component_catalog.h
matter/efr32/efr32mg12/BRD4170A/autogen/sl_event_handler.c
matter/efr32/efr32mg12/BRD4170A/autogen/sl_spidrv_init.c
matter/efr32/efr32mg12/BRD4170A/autogen/sl_spidrv_instances.h
matter/efr32/efr32mg12/BRD4170A/config/brd4161a.h
matter/efr32/efr32mg12/BRD4170A/config/sl_spidrv_exp_config.h
matter/efr32/efr32mg12/BRD4170A/config/spidrv_config.h

MG12 63A/64A/70A Board bring up
Problem / Feature
What is being fixed? What is the feature being added? Examples:
Added changes to initialize MG12 - 70A/63A/64A Boards
Changes include Wi-Fi initialization and SPI pin Configuration w.r.t RS9116 and WF200
Testing
How was this tested?
Manually Tested below scenario's
Build is successful
Commissioning is successful
Sanity completed with MG12-70A/63A/64A with RS9116 and WF200 on one application (Lighting App).

[EFR32] MG12 63A/64A/70A Board bring up (#85)

---

platform/emdrv/nvm3/src/nvm3_hal_flash_ccp.c

SiWx917 disconnecting during nvm3 open. 
Adding delay to resolve target connection lost (mcu reset) issue in SiWx917 SOC
Tested locally, the mcu is not resetting

Added delay in nvm3 open so that SiWx917 doesn't disconnect

---

matter/efr32/efr32mg12/BRD4162A/autogen/sl_event_handler.c
matter/efr32/efr32mg12/BRD4163A/autogen/sl_event_handler.c
matter/efr32/efr32mg12/BRD4164A/autogen/sl_event_handler.c
matter/efr32/efr32mg12/BRD4166A/autogen/sl_event_handler.c
matter/efr32/efr32mg12/BRD4170A/autogen/sl_event_handler.c
matter/efr32/efr32mg12/BRD4304A/autogen/sl_event_handler.c
matter/efr32/efr32mg24/BRD2601B/autogen/sl_event_handler.c
matter/efr32/efr32mg24/BRD2703A/autogen/sl_event_handler.c
matter/efr32/efr32mg24/BRD4186A/autogen/sl_event_handler.c
matter/efr32/efr32mg24/BRD4187A/autogen/sl_event_handler.c

Problem
What is being fixed? Examples:
Earlier all the applications use EFR32 BLE with RS9116 boards.
Change Overview
In this PR, we enabled RS9116 BLE for all the applications.
Testing
Tested manually by using MG12+RS9116
Tested manually by using MG24+RS9116

Added changes for RS9116 BLE integration

---

platform/emdrv/nvm3/src/nvm3_hal_flash_ccp.c

nvm3 open was failing for 40k nvm3 size due to incorrect page size for 917 SoC
Increased the page size from 1024 to 2048 (Matching to efr32 nvm page size)
halInfo->pageSize = 2048;
*Tested locally (917 SoC)

SiWx917 SoC -Increasing the nvm page size for 917 SoC

---

matter/mbedtls/tinycrypt/inc/mbedtls/pk.h

What is being fixed? 
- Both the definitions are defined under the same macro(**MBEDTLS_RSA_C**) and implementation is almost same, so removed.
what is being tested?
- MG24+RS9116,MG24+WF200,SiWx917 on lighting app(commissioning and unicast command)

removed mbedtls pk rsa redefinition

---

matter/efr32/efr32mg24/BRD4186C/config/brd4186c.h

Wakeup and sleep pin correction for BRD4186C

[Sleepy] sleep and wakeup pin correction for the brd4186c

---

matter/efr32/efr32mg12/BRD4161A/config/brd4161a.h

Correcting the sleepy pins on MG12
However it is not required for SMG since we are not supporting sleepy for mg12 boards but still good to have correct one

[Silabs]fixing the pins for mg12 boards

---

matter/efr32/efr32mg12/BRD4161A/autogen/sl_event_handler.c
matter/efr32/efr32mg12/BRD4162A/autogen/sl_event_handler.c
matter/efr32/efr32mg12/BRD4163A/autogen/sl_event_handler.c
matter/efr32/efr32mg12/BRD4164A/autogen/sl_event_handler.c
matter/efr32/efr32mg12/BRD4166A/autogen/sl_event_handler.c
matter/efr32/efr32mg12/BRD4170A/autogen/sl_event_handler.c
matter/efr32/efr32mg12/BRD4304A/autogen/sl_event_handler.c
matter/efr32/efr32mg24/BRD2601B/autogen/sl_event_handler.c
matter/efr32/efr32mg24/BRD2703A/autogen/sl_event_handler.c
matter/efr32/efr32mg24/BRD4186A/autogen/sl_event_handler.c
matter/efr32/efr32mg24/BRD4186C/autogen/sl_event_handler.c
matter/efr32/efr32mg24/BRD4187A/autogen/sl_event_handler.c
matter/efr32/efr32mg24/BRD4187C/autogen/sl_event_handler.c
matter/efr32/mgm24/BRD2704A/autogen/sl_event_handler.c
matter/efr32/mgm24/BRD4316A/autogen/sl_event_handler.c
matter/efr32/mgm24/BRD4317A/autogen/sl_event_handler.c
matter/efr32/mgm24/BRD4318A/autogen/sl_event_handler.c
matter/efr32/mgm24/BRD4319A/autogen/sl_event_handler.c

Part of the fix for https://jira.silabs.com/browse/MATTER-1695 . 
Moving NVM initialization to sl_platform_init(). A Matter CSA repo PR will move the initialization out of SilabsConfig::Init()
Verified that a lighting app on BRD4161A successfully boots with this and a corresponding change to SilabsConfig::Init()

Initialize NVM in sl_platform_init()

---

matter/efr32/efr32mg12/BRD4161A/config/sl_mbedtls_config.h
matter/efr32/efr32mg12/BRD4162A/config/sl_mbedtls_config.h
matter/efr32/efr32mg12/BRD4163A/config/sl_mbedtls_config.h
matter/efr32/efr32mg12/BRD4164A/config/sl_mbedtls_config.h
matter/efr32/efr32mg12/BRD4166A/config/sl_mbedtls_config.h
matter/efr32/efr32mg12/BRD4170A/config/sl_mbedtls_config.h
matter/efr32/efr32mg12/BRD4304A/config/sl_mbedtls_config.h
matter/efr32/efr32mg24/BRD2601B/config/sl_mbedtls_config.h
matter/efr32/efr32mg24/BRD2703A/config/sl_mbedtls_config.h
matter/efr32/efr32mg24/BRD4186A/config/sl_mbedtls_config.h
matter/efr32/efr32mg24/BRD4186C/config/sl_mbedtls_config.h
matter/efr32/efr32mg24/BRD4187A/config/sl_mbedtls_config.h
matter/efr32/efr32mg24/BRD4187C/config/sl_mbedtls_config.h
matter/efr32/mgm24/BRD2704A/config/sl_mbedtls_config.h
matter/efr32/mgm24/BRD4316A/config/sl_mbedtls_config.h
matter/efr32/mgm24/BRD4317A/config/sl_mbedtls_config.h
matter/efr32/mgm24/BRD4318A/config/sl_mbedtls_config.h
matter/efr32/mgm24/BRD4319A/config/sl_mbedtls_config.h
matter/mbedtls/tinycrypt/inc/mbedtls/config.h

`OPENTHREAD_CONFIG_COAP_SECURE_API_ENABLE` shouldn't be used with the coap library.
Doesn't get set one the crypto files get compiled.
Use a configuration define to set correct configs

Replace OT define with the correct define

---

matter/si91x/siwx917/BRD4325x/support/hal/rsi_hal_mcu_m4.c

Using BTN1 release interrupt, Since window-app requires.

[Wi-Fi] Adds fix for 917SoC window-app crash with button 1

---

matter/si91x/siwx917/BRD4325x/autogen/sl_event_handler.c

* Synchronize the autogen file(s) for WiseConnect 3.0.13
* Updates autogen files to reflect NVIC API changes for WiseConnect 3.0.13
* >If manually tested, what platforms controller and device platforms were manually tested, and how?
Tested manually for sanity on BRD4325B (DUAL FLASH) and BRD4388 (COMMON FLASH)

Ports NVIC API from autogenerated files for WiseConnect 3.0.13

---

matter/si91x/siwx917/BRD4338A/autogen/sl_event_handler.c

Disabling Sleep Initialization code in BRD4338A for enabling LCD.
This will activated in sleep path.

Enabling LCD module

---

matter/efr32/efr32mg12/BRD4161A/config/sl_uartdrv_usart_vcom_config.h
matter/efr32/efr32mg12/BRD4163A/config/sl_uartdrv_usart_vcom_config.h
matter/efr32/efr32mg12/BRD4164A/config/sl_uartdrv_usart_vcom_config.h
matter/efr32/efr32mg12/BRD4304A/config/sl_uartdrv_usart_vcom_config.h
matter/efr32/efr32mg24/BRD2703A/config/sl_uartdrv_eusart_vcom_config.h
matter/efr32/efr32mg24/BRD4186A/config/sl_uartdrv_eusart_vcom_config.h
matter/efr32/efr32mg24/BRD4186C/config/sl_uartdrv_eusart_vcom_config.h
matter/efr32/efr32mg24/BRD4187A/config/sl_uartdrv_eusart_vcom_config.h
matter/efr32/efr32mg24/BRD4187C/config/sl_uartdrv_eusart_vcom_config.h
matter/efr32/mgm24/BRD4316A/config/sl_uartdrv_eusart_vcom_config.h
matter/efr32/mgm24/BRD4317A/config/sl_uartdrv_eusart_vcom_config.h
matter/efr32/mgm24/BRD4318A/config/sl_uartdrv_eusart_vcom_config.h
matter/efr32/mgm24/BRD4319A/config/sl_uartdrv_eusart_vcom_config.h

On some boards, flow control was configured to hardware when we do not use it for Matter shells
Change VCOM config to not use flow control
Manual tests with BRD4187C, 86C and 2601B.

Update VCOM configurations to remove Flow Control

---

matter/si91x/siwx917/BRD4338A/support/hal/rsi_hal_mcu_m4.c

* Updated the header file name which renamed in wifi-sdk
* Updated the state changes for the button interrupts which were modified from wifi-sdk
> Now we are getting 0 on press and 1 on release from the interrupt

[WiFi] - Adds changes required for wifi-sdk 3.1.1

---

matter/si91x/siwx917/BRD4338A/support/src/sl_si91x_m4_ps.c

The device was getting crashed after commissioning. The LWIP_PBUF_POOL size was increase from 16 to 32 in https://github.com/project-chip/connectedhomeip/commit/649e991b07f0d2f938168977069c01e8e617631e PR due to which we need to retain some extra RAM
Increase the RAM retention from 256KB to 320KB, so that before going to sleep total Ram can be retained
Tested manually

[SiWx917][Sleepy] Increase the ram retention from 256k to 320k

---

matter/si91x/siwx917/BRD4338A/support/inc/sl_si91x_m4_ps.h
matter/si91x/siwx917/BRD4338A/support/src/sl_si91x_m4_ps.c

To use the sleepy alarm based API's in the rejoin calls
For sleepy app, alarm based wakeup API's were enclosed in macro due to which it cannot be used standalone. Alarm based wakeup is used in sleepy rejoin so that the device can go to sleepy/wakeup without any duplicating this code
Tested manually

[SiWx917] Enabling the alarm API's which will be used in rejoin sleep

---

matter/si91x/siwx917/BRD4338A/support/src/sl_si91x_m4_ps.c

Setting M4 P2P register was handled before calling in sleep, which is (wifi sdk 3.1.3) now handled in the sleep API itself 
commenting the Register set
Tested locally

[SiWx917] Removing the register set from trigger sleep

---

matter/si91x/siwx917/BRD4338A/autogen/sl_event_handler.c
matter/si91x/siwx917/BRD4338A/support/inc/sl_si91x_m4_ps.h
matter/si91x/siwx917/BRD4338A/support/src/sl_si91x_m4_ps.c

This commit introduced features that were not compatible with current CSA wifi_sdk version and are dependent on unreleased code....

Revert "Refactors needed for M4 power save on SiWx917 (#177)"

---

matter/mbedtls/tinycrypt/src/pk.c

It is possible that the pkinfo of the used pk context is uninitialized. Add a check to make sure it has a free function before calling it
this fixes MATTER-3426 in the context of provisioned certificates

Add Null check for a function pointer that might not be set

---

matter/efr32/efr32mg12/BRD4161A/config/psa_crypto_config.h
matter/efr32/efr32mg12/BRD4162A/config/psa_crypto_config.h
matter/efr32/efr32mg12/BRD4163A/config/psa_crypto_config.h
matter/efr32/efr32mg12/BRD4164A/config/psa_crypto_config.h
matter/efr32/efr32mg12/BRD4166A/config/psa_crypto_config.h
matter/efr32/efr32mg12/BRD4170A/config/psa_crypto_config.h
matter/efr32/efr32mg12/BRD4304A/config/psa_crypto_config.h
matter/efr32/efr32mg24/BRD2601B/config/psa_crypto_config.h
matter/efr32/efr32mg24/BRD2703A/config/psa_crypto_config.h
matter/efr32/efr32mg24/BRD4186A/config/psa_crypto_config.h
matter/efr32/efr32mg24/BRD4186C/config/psa_crypto_config.h
matter/efr32/efr32mg24/BRD4187A/config/psa_crypto_config.h
matter/efr32/efr32mg24/BRD4187C/config/psa_crypto_config.h
matter/efr32/mgm24/BRD2704A/config/psa_crypto_config.h
matter/efr32/mgm24/BRD4316A/config/psa_crypto_config.h
matter/efr32/mgm24/BRD4317A/config/psa_crypto_config.h
matter/efr32/mgm24/BRD4318A/config/psa_crypto_config.h
matter/efr32/mgm24/BRD4319A/config/psa_crypto_config.h

PSA crypt keys created with drivers V1+V2 cannot be used by applications running driver V3 alone. This causes Matter application to stop working when updated to latest GSDK.
Drivers V1 and V2 enabled for all boards. This enables PSA to automatically upgrade old keys to V3.
Tested on EFR32MG12.

PSA Crypto: Enabled compatibility with drivers V1 and V2.

---

matter/si91x/siwx917/BRD4338A/support/hal/rsi_hal_mcu_m4.c

Problem / Feature
Timers are inconsistent with non-sleepy applications
Change overview
With non-sleepy applications ,RTOS Software Timer drift while using an RC-32MHz as a Core reference Clock. It has been changed to 40MHZ and timers are working accurately
Testing
Tested manually Tc-su_2_01 step 2, tc_su_2_02 step 2, tc_su_2_05 step 3 and tc_su_2_05 step 4

[SiWx917] Added fixes for 917 SoC timer issue 

---

matter/efr32/efr32mg24/BRD2601B/autogen/sl_ot_custom_cli.c
matter/efr32/efr32mg24/BRD2601B/autogen/sl_ot_init.c
matter/efr32/efr32mg24/BRD2703A/autogen/sl_ot_custom_cli.c
matter/efr32/efr32mg24/BRD2703A/autogen/sl_ot_init.c
matter/efr32/efr32mg24/BRD4186A/autogen/sl_ot_custom_cli.c
matter/efr32/efr32mg24/BRD4186A/autogen/sl_ot_init.c
matter/efr32/efr32mg24/BRD4186C/autogen/sl_ot_custom_cli.c
matter/efr32/efr32mg24/BRD4186C/autogen/sl_ot_init.c
matter/efr32/efr32mg24/BRD4187A/autogen/sl_ot_custom_cli.c
matter/efr32/efr32mg24/BRD4187A/autogen/sl_ot_init.c
matter/efr32/efr32mg24/BRD4187C/autogen/sl_ot_custom_cli.c
matter/efr32/efr32mg24/BRD4187C/autogen/sl_ot_init.c
matter/efr32/efr32mg26/BRD2608A/autogen/sl_ot_custom_cli.c
matter/efr32/efr32mg26/BRD2608A/autogen/sl_ot_init.c
matter/efr32/efr32mg26/BRD4116A/autogen/sl_ot_custom_cli.c
matter/efr32/efr32mg26/BRD4116A/autogen/sl_ot_init.c
matter/efr32/efr32mg26/BRD4117A/autogen/sl_ot_custom_cli.c
matter/efr32/efr32mg26/BRD4117A/autogen/sl_ot_init.c
matter/efr32/efr32mg26/BRD4118A/autogen/sl_ot_custom_cli.c
matter/efr32/efr32mg26/BRD4118A/autogen/sl_ot_init.c
matter/efr32/mgm24/BRD2704A/autogen/sl_ot_custom_cli.c
matter/efr32/mgm24/BRD2704A/autogen/sl_ot_init.c
matter/efr32/mgm24/BRD4316A/autogen/sl_ot_custom_cli.c
matter/efr32/mgm24/BRD4316A/autogen/sl_ot_init.c
matter/efr32/mgm24/BRD4317A/autogen/sl_ot_custom_cli.c
matter/efr32/mgm24/BRD4317A/autogen/sl_ot_init.c
matter/efr32/mgm24/BRD4318A/autogen/sl_ot_custom_cli.c
matter/efr32/mgm24/BRD4318A/autogen/sl_ot_init.c
matter/efr32/mgm24/BRD4319A/autogen/sl_ot_custom_cli.c
matter/efr32/mgm24/BRD4319A/autogen/sl_ot_init.c

* OT User CLI commands was getting init even if the OT cli was disable which caused an assert in the OT stack init
* OT adds an EM1 req in the sleepy which never gets removed
* Ifdef guard the cli init
* Temporary remove the EM1 req until OT fixes its issue
* Manual tests

Fix OT Cli init and Power Manager req

---

matter/mbedtls/tinycrypt/inc/mbedtls/build_info.h
matter/si91x/siwx917/BRD4338A/config/sl_mbedtls_config.h

To support Tinycript and PSA, the generated file was modified to accommodated the different requirements of both crypto solution. This forced us to maintain a changed in the generated files.
PR moves the custom change out of the generated file to reduce the amount of changes in the generated files.
Manually tested to make sure the device can still work.

Remove build_info workaround from the generated files

---

matter/mbedtls/tinycrypt/inc/mbedtls/build_info.h

For SLC builds, we need a way to include the hardcoded mbedtls config without conflicting with the mbedtls config component. 
This define can be set by SLC to include it without affecting CSA builds that do not require this define.
Manual tests

Add include for user config as an SLC fix

---

matter/si91x/siwx917/BRD4338A/autogen/sl_si91x_power_manager_wakeup_handler.c
matter/si91x/siwx917/BRD4338A/autogen/sl_si91x_power_manager_wakeup_handler.h
matter/si91x/siwx917/BRD4338A/config/sl_si91x_power_manager_wakeup_source_config.h

* BTN0 is not working properly in sleep enabled applications.
Adds the BTN0 as a wakeup source for sleep enabled applications on SiWx917
It was tested manually on the SiWx917 lock application.

Adds the BTN0 wakeup source for SiWx917

---

components/service/network_manager/src/sl_net_for_lwip.c

The `sl_net_for_lwip.c` in the wifi sdk has several compilation and code issue preventing from being it used.
This file a few modification to fix these until the wifi sdk fixes this.
Manual tests with the 917 refactor

Add modified sl net lwip file for Wi-Fi refactor

---

matter/si91x/support/hal/rsi_hal_mcu_m4.c

What is being fixed?
Add `sl_component_catalog.h` header to access SL_CATALOG_SIMPLE_BUTTON_PRESENT define.

Adds header to verify SL COMPONENT CATALOG

---

matter/efr32/efr32mg24/BRD4186C/autogen/sl_event_handler.c
matter/efr32/efr32mg24/BRD4186C/autogen/sl_spidrv_init.c
matter/efr32/efr32mg24/BRD4186C/autogen/sl_spidrv_instances.h
matter/efr32/efr32mg24/BRD4187C/autogen/sl_event_handler.c
matter/efr32/efr32mg24/BRD4187C/autogen/sl_spidrv_init.c
matter/efr32/efr32mg24/BRD4187C/autogen/sl_spidrv_instances.h

917 ncp autogen files updated as USART is used for SPI based on wifi sdk 3.4.0.
slc generate for EFR32 mg24 and 917 ncp autogen files and edited the files according to the USART.
Verified builds app for EFR32 mg24 and 917 NCP board.
and commission test.

Updates for 917 ncp autogen files

---

matter/si91x/support/hal/rsi_hal_mcu_m4.c

With the wifi sdk v3.4.1-rc2, the btn irq handled is modified hence the state changes are now correct
Changing the button handling and passing the correct parameter
Pressed -> 1
Release -> 0
Tested locally
Note: This will break the CSA if this pointer is added, since it fixes the v3.4.1-rc2 and CSA is on v3.4.0 only

Fixing the button IRQ state with the wifi sdk v3.4.1
